server:
  port: 8182
  servlet:
    context-path: /simple-store-cart

integrations:
  product-service:
    url: http://localhost:8183/simple-store-core/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

cart-service:
  cart-prefix: simple_cart_